### ISSUE TITLE
Trying to close the TV when it is already closed crashes homebridge

### ISSUE THREAD

**Issue by el** [dvcrn/homebridge-netcast-tv#1]
**Describe The Bug:**
If you use Siri or a scene to close TV when it is already closed, homebridge crashes with the following error:

**To Reproduce:**
- Close TV
- Ask Siri to close the tv

**Expected behavior:**
- No crashes :)

**Logs:**

```
FetchError: request to http://192.168.31.224:8080/roap/api/auth failed, reason: connect EHOSTUNREACH 192.168.31.224:8080
    at ClientRequest.<anonymous> (/usr/lib/node_modules/homebridge-netcast-tv/node_modules/node-fetch/lib/index.js:1461:11)
    at ClientRequest.emit (events.js:315:20)
    at Socket.socketErrorListener (_http_client.js:469:9)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  type: 'system',
  errno: 'EHOSTUNREACH',
  code: 'EHOSTUNREACH'
}
```

**Plugin Config:**

```json

        {
            "devices": [
                {
                    "name": "LG TV",
                    "host": "192.168.31.224",
                    "mac": "xxx",
                    "accessToken": "xxx",
                    "keyInputDelay": 600,
                    "offPauseDuration": 600000,
                    "channels": [
                        {
                            "name": "Apple TV",
                            "type": "external",
                            "channel": {
                                "inputSourceType": "6",
                                "inputSourceIdx": "6"
                            }
                        }
                    ]
                }
            ],
            "platform": "netcasttv"
        }
```

**Environment:**

* **Plugin Version**: v2.0.2
* **Homebridge Version**: v1.1.7
* **Node.js Version**: v14.15.5
* **NPM Version**: -v6.14.11
* **Operating System**: Raspbian

**Comment by dvcrn** [comment]
Thanks for reporting, looks like an uncaught error

**Comment by esolm** [comment]
Hey David! 
Thanks a lot for developing this code! It is very useful. However I still have the same problem from years ago. 
Could you be so kind of resolving this issue? 

Thanks!
<img width="1275" alt="image" src="https://user-images.githubusercontent.com/47225779/205515254-7500220c-1125-4163-a677-303f72d1fb0f.png">

**Comment by dvcrn** [comment]
Hi, I don't have a netcast tv anymore so I'm reliant on other people to work on this

The error from your screenshot looks different to the error from this report. Yours is a timeout, while the one from OP is EHOSTUNREACH
