### ISSUE TITLE
Plugin crashes and homebridge restarts

### ISSUE THREAD

**Issue by l0rda** [dvcrn/homebridge-netcast-tv#3]
**Describe The Bug:**
Plugin crashes and homebridge restarts when i try to turn on tv via home app.
Turn off is working fine.

**To Reproduce:**
Turn on tv via homekit

**Expected behavior:**
TV must be turned on

**Logs:**

```
[1/3/2022, 4:39:20 PM] [netcasttv] set Active Identifier => setNewValue: 0
[1/3/2022, 4:41:15 PM] Error: Request timed out
    at NetcastClient.send_to_tv (/homebridge/node_modules/homebridge-netcast-tv/node_modules/lg-netcast/dist/netcast.js:209:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at NetcastClient.get_session (/homebridge/node_modules/homebridge-netcast-tv/node_modules/lg-netcast/dist/netcast.js:246:21)
    at LgNetcastTV.sendAuthorizedCommand (/homebridge/node_modules/homebridge-netcast-tv/src/platformAccessory.ts:333:23)
    at Active.<anonymous> (/homebridge/node_modules/homebridge-netcast-tv/src/platformAccessory.ts:130:9)
[1/3/2022, 4:41:15 PM] Got SIGTERM, shutting down Homebridge...
[1/3/2022, 4:41:20 PM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
```

**Plugin Config:**

```json
        {
            "devices": [
                {
                    "name": "LG TV 49",
                    "host": "192.168.1.201",
                    "mac": "cc:cc:cc:cc:cc:cc",
                    "accessToken": "999999",
                    "keyInputDelay": 600,
                    "offPauseDuration": 600000
                }
            ],
            "platform": "netcasttv"
        }
```

**Environment:**
* **TV**: LG 49UB820V Software 04.12.36 SDK 03.05
* **Plugin Version**: homebridge-netcast-tv v2.0.2
* **Homebridge Version**: v1.3.9 
* **Node.js Version**: v16.13.1
* **NPM Version**: v8.1.2
* **Operating System**: docker on x86_64 linux, macvlan network (homebridge and tv in same network)

**Comment by l0rda** [comment]
OK, I read.
Turning on the TV is not supported. But is think it must not restart homebridge.
